logging:
    level:
        org:
            hibernate:
                stat: debug
                type: trace
server:
    port: 8180 
    servlet:
        context-path: /authors/v1
spring:
    datasource:
        driverClassName: org.h2.Driver
        password: ''
        url: jdbc:h2:mem:authorsDB
        username: sa
    h2:
        console:
            enabled: true
            path: /h2-authors
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        generate-ddl: true
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                format_sql: true
                generate_statistics: true
        show-sql: true
eureka:
    client:
        service-url:
            default-zone: http://localhost:8761/eureka